# Source: vault/templates/server-config-configmap.yaml
#
# tcp Listener Parameters
# address (string: "127.0.0.1:8200") – Specifies the address to bind to for listening.
# cluster_address (string: "127.0.0.1:8201") – Specifies the address to bind to for cluster server-to-server requests. 
# This defaults to one port higher than the value of address. This does not usually need to be set, 
# but can be useful in case Vault servers are isolated from each other in such a way that they need 
# to hop through a TCP load balancer or some other scheme in order to talk.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
  labels:
    helm.sh/chart: vault-0.10.0
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
data:
  extraconfig-from-values.hcl: |-
    disable_mlock = true
    ui = true
    listener "tcp" {
      # tls_disable = 1
      tls_disable = 0
      # address = "[::]:8200"
      address = "0.0.0.0:8200"
      cluster_address = "[::]:8201"
      tls_cert_file = "/vault/ssl/vault.pem"
      tls_key_file = "/vault/ssl/vault-key.pem"
      tls_min_version = "tls12"
    }
    storage "file" {
      path = "/vault/data"
    }
    
    # Example configuration for using auto-unseal, using Google Cloud KMS. The
    # GKMS keys must already exist, and the cluster must have a service account
    # that is authorized to access GCP KMS.
    #seal "gcpckms" {
    #   project     = "vault-helm-dev"
    #   region      = "global"
    #   key_ring    = "vault-helm-unseal-kr"
    #   crypto_key  = "vault-helm-unseal-key"
    #}
---